mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('trackercurses/', include('trackercurses.urls')),   
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),

    path('polls', views.PollsView.as_view(), name='mysite'),

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    path('<int:question_id>/vote', views.vote, name='vote'),
    ]

trackercurses/urls.py
from django.urls import path
from .views.curso_views import *
from .views.usuario_views import *

app_name = 'trackercurses'
urlpatterns = [
    path('', listar_cursos, name='listar_cursos'),
    path('listar_cursos/', listar_cursos, name='listar_cursos'),
    path('cadastrar_curso/', cadastrar_curso, name="cadastrar_curso"),
    path('editar_curso/<int:id>', editar_curso, name="editar_curso"),
    path('remover_curso/<int:id>', remover_curso, name="remover_curso"),
    path('cadastrar_usuario/', cadastrar_usuario, name="cadastrar_usuario"),
    path('logar_usuario/', logar_usuario, name="logar_usuario"),
    path('deslogar_usuario/', deslogar_usuario, name="deslogar_usuario"),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data de publicação')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1)<=self.pub_date<=now
    was_published_recently.admin_order_fied = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Publicada recentemente?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Autor(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    nome_autor = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    cidade = models.CharField(max_length=200)
    def __str__(self):
        return self.nome_autor

trackercurses/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Curso(models.Model):
    PRIORIDADE_CHOICES = [
        ("A", "Alta"),
        ("N", "Normal"),
        ("B", "Baixa")
    ]
    titulo = models.CharField(max_length=30, null=False, blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, null=False, blank=False)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

trackercurses/forms.py
from django import forms
from .models import Curso


class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        exclude = ('usuario', )
        fields = '__all__'

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

def index(request):
    return render(request, 'polls/index.html')

class PollsView(generic.ListView):
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte = timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{
            'question':question,
            'error_message': "Você não selecionou uma opção!",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

trackercurses/views/curso_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..forms import CursoForm
from ..entidades.curso import Curso
from ..services import curso_service

# Create your views here.


@login_required()
def listar_cursos(request):
    cursos = curso_service.listar_cursos(request.user)
    return render(request, 'cursos/listar_cursos.html', {"cursos": cursos})


@login_required()
def cadastrar_curso(request):
    if request.method == "POST":
        form_curso = CursoForm(request.POST)
        if form_curso.is_valid():
            titulo = form_curso.cleaned_data["titulo"]
            descricao = form_curso.cleaned_data["descricao"]
            data_expiracao = form_curso.cleaned_data["data_expiracao"]
            prioridade = form_curso.cleaned_data["prioridade"]
            curso_nova = Curso(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                                 prioridade=prioridade, usuario=request.user)
            curso_service.cadastrar_curso(curso_nova)
            return redirect('listar_cursos')
    else:
        form_curso = CursoForm()
    return render(request, 'cursos/form_curso.html', {"form_curso": form_curso})


@login_required()
def editar_curso(request, id):
    curso_bd = curso_service.listar_curso_id(id)
    if curso_bd.usuario != request.user:
        return HttpResponse("Não permitido")
    form_curso = CursoForm(request.POST or None, instance=curso_bd)
    if form_curso.is_valid():
        titulo = form_curso.cleaned_data["titulo"]
        descricao = form_curso.cleaned_data["descricao"]
        data_expiracao = form_curso.cleaned_data["data_expiracao"]
        prioridade = form_curso.cleaned_data["prioridade"]
        curso_nova = Curso(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                             prioridade=prioridade, usuario=request.user)
        curso_service.editar_curso(curso_bd, curso_nova)
        return redirect('listar_cursos')
    return render(request, 'cursos/form_curso.html', {"form_curso": form_curso})


@login_required()
def remover_curso(request, id):
    curso_bd = curso_service.listar_curso_id(id)
    if curso_bd.usuario != request.user:
        return HttpResponse("Não permitido")
    if request.method == "POST":
        curso_service.remover_curso(curso_bd)
        return redirect('listar_cursos')
    return render(request, 'cursos/confirma_exclusao.html', {'curso': curso_bd})

trackercurses/views/usuario_views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def cadastrar_usuario(request):
    if request.method == "POST":
        form_usuario = UserCreationForm(request.POST)
        if form_usuario.is_valid():
            form_usuario.save()
            return redirect('listar_cursos')
    else:
        form_usuario = UserCreationForm()
    return render(request, 'usuarios/form_usuario.html', {"form_usuario": form_usuario})


def logar_usuario(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('listar_cursos')
        else:
            messages.error(request, 'As credenciais de usuário estão incorretas')
            return redirect('logar_usuario')
    else:
        form_login = AuthenticationForm()
    return render(request, 'usuarios/login.html', {"form_login": form_login})


def deslogar_usuario(request):
    logout(request)
    return redirect('logar_usuario')

polls/templates/polls/detail.html
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all  %}
        <input type="radio" name="choice"
        id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>

polls/templates/polls/detail_autor.html
<h1>{{nome_autor }}</h1>
{% if latest_question_list%}
<ul>
    {% for question in latest_question_list %}


        <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>
            ----Data de publicação: {{question.pub_date}}
        </li>
        <br>

    {% endfor %}

    <br>
    <a href="{% url 'polls:index' %}">Página Inicial</a>
</ul>
    {% else %}
    <p>Nenhuma questão disponível!</p>
{% endif%}

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aplicações DSWeb 2020.1</title>
</head>
<body>
    <h1>Aplicações da Disciplina DSWeb 2020.1</h1>
    <h3>Selecione a aplicação desejada:</h3>
    <ul>
        <li><a href="{% url 'polls:mysite' %}">Aplicação Enquete - Módulo 1</a></li>
        <li><a href="{% url 'trackercurses:index' %}">TrackerCurses - Módulo 2</a></li>
    </ul>
</body>
</html>

polls/templates/polls/question_list.html
{% block %}Lista das Últimas Enquetes{% endblock %}

    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">
                    {{ question_text|truncatewords:30 }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>Não há enquetes cadastradas até o momento!</h3>
    {% endif %}


<!--{% load static %}-->
<!--<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">-->

<!--{% block titulo %}Lista das Últimas Enquetes{% endblock %}-->

<!--{% if latest_question_list %}-->
<!--<ul>-->
<!--    {% for question in latest_question_list %}-->
<!--        <li><a href="{% url 'polls:detail' question.id %}"> {{question.question_text}}</a></li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--{% else %}-->
<!--    <p>Nenhuma questão disponível!</p>-->
<!--{% endif%}-->

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }}
            voto{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Votar novamente?</a>

trackercurses/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gerenciador de Cursos</title>
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Gerencidor de Cursos - APP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'listar_cursos' %}">Listar Cursos</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'deslogar_usuario' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    <main class="container">
        {% block conteudo %}
        {% endblock conteudo %}
    </main>
</body>
</html>

trackercurses/templates/cursos/confirma_exclusao.html
{% extends 'base.html'%}

{% block conteudo %}
<div class="card mb-3">
    <div class="card-header">
        Tem certeza que deseja remover a curso abaixo?
    </div>
    <div class="card-body">
        <h5 class="card-title">{{curso.titulo}}</h5>
        <p class="card-text">{{curso.descricao}}</p>
        <hr>
        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>
        </form>
    </div>
</div>
{% endblock conteudo %}

trackercurses/templates/cursos/form_curso.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form_curso.titulo.errors }}
        <label>Título: </label>
        {{ form_curso.titulo | addclass:'form-control' }}
    </div>
    <div class="form-group">
        {{ form_curso.descricao.errors }}
        <label>Descrição: </label>
        {{ form_curso.descricao | addclass:'form-control'}}
    </div>
    <div class="form-group">
        {{ form_curso.data_expiracao.errors }}
        <label>Data de expiração: </label>
        {{ form_curso.data_expiracao | addclass:'form-control'}}
    </div>
    <div class="form-group">
        {{ form_curso.prioridade.errors }}
        <label>Prioridade: </label>
        {{ form_curso.prioridade | addclass:'form-control'}}
    </div>

    <div class="form-group">
        <input type="submit" value="Salvar">
    </div>

</form>
{% endblock conteudo %}

trackercurses/templates/cursos/listar_cursos.html
{% extends 'base.html' %}

{% block conteudo %}
<h1>Listagem de cursos</h1>
{% for curso in cursos%}
<div class="card mb-3">
    <div class="card-header">
        {{ curso.get_prioridade_display }}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{curso.titulo}}</h5>
        <p class="card-text">{{curso.descricao}}</p>
        <hr>
        <a href="{% url 'editar_curso' curso.id %}">Alterar Tarefa</a>
        <a href="{% url 'remover_curso' curso.id %}">Remover Tarefa</a>
    </div>
</div>
{% endfor %}
<a href="{% url 'cadastrar_curso' %}"><input type="button" class="btn btn-primary mb-3" value="Cadastrar Tarefa"></a>
{% endblock conteudo %}

trackercurses/templates/usuarios/form_usuario.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}
<form method="post">
    {% csrf_token %}

    <div class="form-group">
        {{ form_usuario.username.errors }}
        <label>Usuário: </label>
        {{form_usuario.username | addclass:'form-control'}}
    </div>

    <div class="form-group">
        {{ form_usuario.password1.errors }}
        <label>Senha: </label>
        {{form_usuario.password1 | addclass:'form-control'}}
    </div>

    <div class="form-group">
        {{ form_usuario.password2.errors }}
        <label>Confirmação de senha: </label>
        {{form_usuario.password2 | addclass:'form-control'}}
    </div>

    <div class="form-group">
        <input type="submit" value="Cadastrar" class="btn btn-primary">
    </div>

</form>
{% endblock conteudo%}

trackercurses/templates/usuarios/login.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}

<form method="post">
    {% csrf_token %}
    {% for message in messages %}
        <div class="alert alert-danger">
            {{message}}
        </div>
    {% endfor %}
    <div class="form-group">
        <label>Usuário: </label>
        {{ form_login.username | addclass:'form-control'}}
    </div>

    <div class="form-group">
        <label>Senha: </label>
        {{ form_login.password | addclass:'form-control'}}
    </div>

    <div class="form-group">
        <input type="submit" value="Entrar" class="btn btn-primary">
    </div>
</form>

<form action="{% url 'cadastrar_usuario' %}" method="get">
    <input type="submit" value="Registrar" class="btn btn-primary">
</form>

{% endblock conteudo %}